CREATE TABLE Utente (
  Email VARCHAR(70) NULL ,
  Password VARCHAR(16) NOT NULL ,
  Descrizione TEXT NULL ,
  Nome VARCHAR(30) NULL ,
  Cognome VARCHAR(30) NULL ,
  Username VARCHAR(16) NOT NULL ,
  DataI DATE NOT NULL ,
  Residenza VARCHAR(100) NULL ,
  PRIMARY KEY (Username(16))
)

CREATE TABLE Post(
  ID INT NOT NULL AUTO_INCREMENT,
  Titolo VARCHAR(50) NOT NULL,
  Messaggio TEXT(500) NOT NULL,
  Utente VARCHAR(16) NOT NULL,
  DataC DATE NOT NULL,
  OraC TIME NOT NULL,
  DataM DATE NULL,
  OraM TIME NULL,
  Luogo VARCHAR(100) NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (Utente) REFERENCES Utente(Username)
)

CREATE TABLE Commento(
  ID INT NOT NULL AUTO_INCREMENT,
  Utente VARCHAR(16) NOT NULL,
  Post INT NOT NULL,
  Messaggio TEXT(250) NOT NULL,
  Data Date NOT NULL,
  Ora TIME NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(Utente) REFERENCES Utente(Username),
  FOREIGN KEY(Post) REFERENCES Post(ID)
)

CREATE TABLE Voti(
  Utente VARCHAR(16) NOT NULL,
  Post INT NOT NULL,
  PRIMARY KEY(Utente, Post),
  FOREIGN KEY(Utente) REFERENCES Utente(Username),
  FOREIGN KEY(Post) REFERENCES Post(ID)
)
